import type { GitHubRepo, RepoWithDetails } from './github'

export const MOCK_REPOS: RepoWithDetails[] = [
  {
    id: 1,
    name: 'react',
    full_name: 'facebook/react',
    description: 'A declarative, efficient, and flexible JavaScript library for building user interfaces.',
    owner: { login: 'facebook' },
    stargazers_count: 228000,
    forks_count: 46500,
    language: 'JavaScript',
    pushed_at: '2024-06-15T10:30:00Z',
    created_at: '2013-05-24T00:00:00Z',
    updated_at: '2024-06-15T10:30:00Z',
    html_url: 'https://github.com/facebook/react',
    languages_url: '',
    commitCount: 18500,
    languages: ['JavaScript', 'TypeScript', 'CSS', 'HTML'],
    topLanguages: ['JavaScript', 'TypeScript', 'CSS'],
  },
  {
    id: 2,
    name: 'next.js',
    full_name: 'vercel/next.js',
    description: 'The React Framework for the Web. Used by some of the world\'s largest companies. Next.js enables you to create high-quality web applications with the power of React components.',
    owner: { login: 'vercel' },
    stargazers_count: 124000,
    forks_count: 26400,
    language: 'TypeScript',
    pushed_at: '2024-06-14T08:15:00Z',
    created_at: '2016-10-05T00:00:00Z',
    updated_at: '2024-06-14T08:15:00Z',
    html_url: 'https://github.com/vercel/next.js',
    languages_url: '',
    commitCount: 15200,
    languages: ['TypeScript', 'JavaScript', 'Rust', 'CSS'],
    topLanguages: ['TypeScript', 'JavaScript', 'Rust'],
  },
  {
    id: 3,
    name: 'tailwindcss',
    full_name: 'tailwindlabs/tailwindcss',
    description: 'A utility-first CSS framework for rapid UI development.',
    owner: { login: 'tailwindlabs' },
    stargazers_count: 82000,
    forks_count: 4100,
    language: 'CSS',
    pushed_at: '2024-06-13T14:45:00Z',
    created_at: '2017-10-06T00:00:00Z',
    updated_at: '2024-06-13T14:45:00Z',
    html_url: 'https://github.com/tailwindlabs/tailwindcss',
    languages_url: '',
    commitCount: 8900,
    languages: ['CSS', 'TypeScript', 'JavaScript'],
    topLanguages: ['CSS', 'TypeScript', 'JavaScript'],
  },
  {
    id: 4,
    name: 'vscode',
    full_name: 'microsoft/vscode',
    description: 'Visual Studio Code is a code editor redefined and optimized for building and debugging modern web and cloud applications.',
    owner: { login: 'microsoft' },
    stargazers_count: 160000,
    forks_count: 27800,
    language: 'TypeScript',
    pushed_at: '2024-06-15T09:00:00Z',
    created_at: '2015-09-03T00:00:00Z',
    updated_at: '2024-06-15T09:00:00Z',
    html_url: 'https://github.com/microsoft/vscode',
    languages_url: '',
    commitCount: 32100,
    languages: ['TypeScript', 'JavaScript', 'CSS', 'Shell'],
    topLanguages: ['TypeScript', 'JavaScript', 'CSS', 'Shell'],
  },
  {
    id: 5,
    name: 'rust',
    full_name: 'rust-lang/rust',
    description: 'Empowering everyone to build reliable and efficient software.',
    owner: { login: 'rust-lang' },
    stargazers_count: 97000,
    forks_count: 12400,
    language: 'Rust',
    pushed_at: '2024-06-15T11:20:00Z',
    created_at: '2010-01-01T00:00:00Z',
    updated_at: '2024-06-15T11:20:00Z',
    html_url: 'https://github.com/rust-lang/rust',
    languages_url: '',
    commitCount: 145000,
    languages: ['Rust', 'Python', 'C', 'Shell'],
    topLanguages: ['Rust', 'Python', 'C', 'Shell'],
  },
  {
    id: 6,
    name: 'three.js',
    full_name: 'mrdoob/three.js',
    description: 'JavaScript 3D Library.',
    owner: { login: 'mrdoob' },
    stargazers_count: 102000,
    forks_count: 35200,
    language: 'JavaScript',
    pushed_at: '2024-06-14T16:30:00Z',
    created_at: '2010-03-23T00:00:00Z',
    updated_at: '2024-06-14T16:30:00Z',
    html_url: 'https://github.com/mrdoob/three.js',
    languages_url: '',
    commitCount: 28500,
    languages: ['JavaScript', 'TypeScript', 'HTML', 'CSS'],
    topLanguages: ['JavaScript', 'TypeScript', 'HTML'],
  },
  {
    id: 7,
    name: 'kubernetes',
    full_name: 'kubernetes/kubernetes',
    description: 'Production-Grade Container Orchestration.',
    owner: { login: 'kubernetes' },
    stargazers_count: 112000,
    forks_count: 38800,
    language: 'Go',
    pushed_at: '2024-06-15T07:45:00Z',
    created_at: '2014-06-06T00:00:00Z',
    updated_at: '2024-06-15T07:45:00Z',
    html_url: 'https://github.com/kubernetes/kubernetes',
    languages_url: '',
    commitCount: 52000,
    languages: ['Go', 'Python', 'Shell', 'PowerShell'],
    topLanguages: ['Go', 'Python', 'Shell'],
  },
  {
    id: 8,
    name: 'pytorch',
    full_name: 'pytorch/pytorch',
    description: 'Tensors and Dynamic neural networks in Python with strong GPU acceleration.',
    owner: { login: 'pytorch' },
    stargazers_count: 83000,
    forks_count: 22500,
    language: 'Python',
    pushed_at: '2024-06-15T12:00:00Z',
    created_at: '2016-08-13T00:00:00Z',
    updated_at: '2024-06-15T12:00:00Z',
    html_url: 'https://github.com/pytorch/pytorch',
    languages_url: '',
    commitCount: 48000,
    languages: ['Python', 'C++', 'Cuda', 'C'],
    topLanguages: ['Python', 'C++', 'Cuda'],
  },
  {
    id: 9,
    name: 'deno',
    full_name: 'denoland/deno',
    description: 'A modern runtime for JavaScript and TypeScript.',
    owner: { login: 'denoland' },
    stargazers_count: 96000,
    forks_count: 5200,
    language: 'Rust',
    pushed_at: '2024-06-14T22:10:00Z',
    created_at: '2018-05-15T00:00:00Z',
    updated_at: '2024-06-14T22:10:00Z',
    html_url: 'https://github.com/denoland/deno',
    languages_url: '',
    commitCount: 12800,
    languages: ['Rust', 'TypeScript', 'JavaScript'],
    topLanguages: ['Rust', 'TypeScript', 'JavaScript'],
  },
  {
    id: 10,
    name: 'flutter',
    full_name: 'flutter/flutter',
    description: 'Flutter makes it easy and fast to build beautiful apps for mobile and beyond.',
    owner: { login: 'flutter' },
    stargazers_count: 163000,
    forks_count: 26700,
    language: 'Dart',
    pushed_at: '2024-06-15T06:30:00Z',
    created_at: '2015-03-06T00:00:00Z',
    updated_at: '2024-06-15T06:30:00Z',
    html_url: 'https://github.com/flutter/flutter',
    languages_url: '',
    commitCount: 31900,
    languages: ['Dart', 'C++', 'Java', 'Objective-C'],
    topLanguages: ['Dart', 'C++', 'Java', 'Objective-C'],
  },
]

export function getMockRepos(): Promise<GitHubRepo[]> {
  return Promise.resolve(
    MOCK_REPOS.map((repo) => ({
      id: repo.id,
      name: repo.name,
      full_name: repo.full_name,
      description: repo.description,
      owner: repo.owner,
      stargazers_count: repo.stargazers_count,
      forks_count: repo.forks_count,
      language: repo.language,
      pushed_at: repo.pushed_at,
      created_at: repo.created_at,
      updated_at: repo.updated_at,
      html_url: repo.html_url,
      languages_url: repo.languages_url,
    }))
  )
}

export function getMockCommitCount(): Promise<number> {
  return Promise.resolve(15000)
}

export function getMockLanguages(): Promise<Record<string, number>> {
  return Promise.resolve({ TypeScript: 10000, JavaScript: 5000, CSS: 2000 })
}
